language: csharp
sudo: required
mono: none
dist: xenial
dotnet: 2.2.300
os:
  - linux
  #- osx
script:
  - dotnet restore
  - dotnet build -c Release test/TensorflowBinariesBuildTask.Tests/TensorflowBinariesBuildTask.Tests.csproj
  - dotnet test -c Release --no-build test/TensorflowBinariesBuildTask.Tests/TensorflowBinariesBuildTask.Tests.csproj
